//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSerio.EvidenceTracker.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSerio.EvidenceTracker.Core.Properties.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Workspace INT = (SELECT ArtifactID FROM EDDSDBO.Artifact WHERE ArtifactTypeID = 8)
        ///
        ///DECLARE @ArtifactTypeID INT = (SELECT DescriptorArtifactTypeID FROM EDDSDBO.ObjectType OT
        ///  INNER JOIN [EDDSDBO].[ArtifactGuid] ARG ON ARG.ArtifactID = OT.ArtifactID
        ///  WHERE ARG.ArtifactGuid = @Type
        ///);
        ///
        ///INSERT INTO [EDDSDBO].[Artifact] (ArtifactTypeID, ParentArtifactID, ContainerID, CreatedOn, CreatedBy, LastModifiedOn, 
        ///									LastModifiedBy, AccessControlListID, AccessControlListIsInherited, TextIdentifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateCase {
            get {
                return ResourceManager.GetString("CreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Workspace INT = (SELECT ArtifactID FROM EDDSDBO.Artifact WHERE ArtifactTypeID = 8)
        ///
        ///DECLARE @ArtifactTypeID INT = (SELECT DescriptorArtifactTypeID FROM EDDSDBO.ObjectType OT
        ///  INNER JOIN [EDDSDBO].[ArtifactGuid] ARG ON ARG.ArtifactID = OT.ArtifactID
        ///  WHERE ARG.ArtifactGuid = @Type
        ///);
        ///
        ///INSERT INTO [EDDSDBO].[Artifact] (ArtifactTypeID, ParentArtifactID, ContainerID, CreatedOn, CreatedBy, LastModifiedOn, 
        ///									LastModifiedBy, AccessControlListID, AccessControlListIsInherited, TextIdentifi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateEvidence {
            get {
                return ResourceManager.GetString("CreateEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [EDDSDBO].[Case].
        /// </summary>
        internal static string GetCases {
            get {
                return ResourceManager.GetString("GetCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT ArtifactID, ControlNumber FROM EDDSDBO.Document WHERE Evidence = {0}.
        /// </summary>
        internal static string GetDocuments {
            get {
                return ResourceManager.GetString("GetDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM [EDDSDBO].[EvidenceTracker].
        /// </summary>
        internal static string GetEvidence {
            get {
                return ResourceManager.GetString("GetEvidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOC
        ///SET DOC.Evidence = {0}
        ///FROM EDDSDBO.Document DOC
        ///WHERE DOC.ArtifactID = {1}.
        /// </summary>
        internal static string UpdateDocument {
            get {
                return ResourceManager.GetString("UpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOC
        ///SET DOC.Evidence = {0}
        ///FROM EDDSDBO.Document DOC
        ///WHERE DOC.ArtifactID = {1}.
        /// </summary>
        internal static string UpdateEvidence {
            get {
                return ResourceManager.GetString("UpdateEvidence", resourceCulture);
            }
        }
    }
}
